name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main # ou la branche que vous voulez déployer
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          working-directory: 'dashfront/front' # Replace with the actual path to your app in your repository
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build --if-present
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs # ou le dossier où se trouve votre site web compilé
